##' 96 simulated growth curves with noise
##' 
##' @name curves
##' @docType data
NULL

##' 96 simulated growth curves without noise
##' 
##' @name curves_ideal
##' @docType data
NULL

##' Truth table for simulated growth curves
##' 
##' @name curves_truth
##' @docType data
NULL

##' Growth curves generated by a Bioscreen C
##' 
##' @name bioscreen
##' @docType data
NULL